import React, { useState, useEffect } from 'react';
import { MoreVertical, Mail, Building, Plus, Edit, Trash2 } from 'lucide-react';
import UserModal from '../../components/modals/UserModal';
import ConfirmationModal from '../../components/modals/ConfirmationModal';
import { User, Organization } from '../../types';
import * as FirestoreService from '../../services/firestore';

export default function AdminUsers() {
  const [users, setUsers] = useState<User[]>([]);
  const [organizations, setOrganizations] = useState<Organization[]>([]);
  const [loading, setLoading] = useState(true);
  const [isModalOpen, setIsModalOpen] = useState(false);
  const [editingUser, setEditingUser] = useState<User | undefined>(undefined);
  const [deleteConfirmation, setDeleteConfirmation] = useState<{
    isOpen: boolean;
    id: string;
  }>({ isOpen: false, id: '' });

  useEffect(() => {
    loadData();
  }, []);

  const loadData = async () => {
    try {
      setLoading(true);
      const [usersData, orgsData] = await Promise.all([
        FirestoreService.getUsers(),
        FirestoreService.getOrganizations()
      ]);
      setUsers(usersData);
      setOrganizations(orgsData);
    } catch (error) {
      console.error("Error loading data:", error);
    } finally {
      setLoading(false);
    }
  };

  const getOrgName = (orgId?: string) => {
    if (!orgId) return '-';
    return organizations.find(o => o.id === orgId)?.name || 'Inconnu';
  };

  const handleSave = async (user: User) => {
    try {
      if (editingUser) {
        await FirestoreService.updateUser(user.id, user);
        setUsers(users.map(u => u.id === user.id ? user : u));
      } else {
        // Check if the user object has a specific ID set (from the modal's authUid)
        // The modal sets user.id to authUid if provided, or randomUUID otherwise.
        // We want to pass this ID to addUser if it was explicitly provided as an Auth UID.
        // However, the modal currently sets a randomUUID if empty.
        // Let's rely on the fact that we updated the modal to pass the ID in the user object.
        // But addUser expects (user, customId).
        
        const { id, ...userData } = user;
        // If the ID looks like a UUID v4 (generated by crypto.randomUUID()), we might treat it as "no custom ID" 
        // if we want Firestore to generate it? 
        // Actually, if the user provided an Auth UID, we want to use it.
        // If they didn't, the modal generated a UUID. 
        // Ideally, we should pass the custom ID separately or check if it was manually entered.
        
        // Let's assume if we are creating a new user, we use the ID provided by the modal as the custom ID.
        // If the modal generated a random one, we'll just use that as the document ID too.
        // This ensures consistency.
        
        const newUser = await FirestoreService.addUser(userData, id);
        setUsers([...users, newUser]);
      }
    } catch (error) {
      console.error("Error saving user:", error);
      alert("Erreur lors de l'enregistrement de l'utilisateur");
    }
  };

  const confirmDelete = (id: string) => {
    setDeleteConfirmation({ isOpen: true, id });
  };

  const handleDelete = async () => {
    try {
      const id = deleteConfirmation.id;
      await FirestoreService.deleteUser(id);
      setUsers(users.filter(u => u.id !== id));
    } catch (error) {
      console.error("Error deleting user:", error);
      alert("Erreur lors de la suppression de l'utilisateur");
    }
  };

  const openNewModal = () => {
    setEditingUser(undefined);
    setIsModalOpen(true);
  };

  const openEditModal = (user: User) => {
    setEditingUser(user);
    setIsModalOpen(true);
  };

  if (loading) {
    return <div className="flex justify-center items-center h-64">Chargement...</div>;
  }

  return (
    <div className="space-y-6">
      <div className="flex flex-col sm:flex-row sm:items-center justify-between gap-4">
        <h1 className="text-2xl font-bold text-gray-900">Utilisateurs</h1>
        <button 
          onClick={openNewModal}
          className="inline-flex items-center px-4 py-2 border border-transparent rounded-md shadow-sm text-sm font-medium text-white bg-indigo-600 hover:bg-indigo-700 focus:outline-none focus:ring-2 focus:ring-offset-2 focus:ring-indigo-500"
        >
          <Plus className="w-5 h-5 mr-2" />
          Ajouter un utilisateur
        </button>
      </div>

      <div className="bg-white shadow-sm rounded-xl border border-gray-100 overflow-hidden">
        <div className="overflow-x-auto">
          <table className="min-w-full divide-y divide-gray-200">
            <thead className="bg-gray-50">
              <tr>
                <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Nom
                </th>
                <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Email
                </th>
                <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Organisation
                </th>
                <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                  Rôle
                </th>
                <th scope="col" className="relative px-6 py-3">
                  <span className="sr-only">Actions</span>
                </th>
              </tr>
            </thead>
            <tbody className="bg-white divide-y divide-gray-200">
              {users.map((user) => (
                <tr key={user.id} className="hover:bg-gray-50">
                  <td className="px-6 py-4 whitespace-nowrap">
                    <div className="flex items-center">
                      <div className="flex-shrink-0 h-10 w-10">
                        <div className="h-10 w-10 rounded-full bg-indigo-100 flex items-center justify-center text-indigo-600 font-bold text-sm">
                          {user.name.charAt(0).toUpperCase()}
                        </div>
                      </div>
                      <div className="ml-4">
                        <div className="text-sm font-medium text-gray-900">{user.name}</div>
                      </div>
                    </div>
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap">
                    <div className="flex items-center text-sm text-gray-500">
                      <Mail className="w-4 h-4 mr-2 text-gray-400" />
                      {user.email}
                    </div>
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap">
                    <div className="flex items-center text-sm text-gray-500">
                      <Building className="w-4 h-4 mr-2 text-gray-400" />
                      {getOrgName(user.organizationId)}
                    </div>
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap">
                    <span className={`px-2 inline-flex text-xs leading-5 font-semibold rounded-full ${
                      user.role === 'admin' ? 'bg-purple-100 text-purple-800' : 'bg-green-100 text-green-800'
                    }`}>
                      {user.role}
                    </span>
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap text-right text-sm font-medium">
                    <div className="flex items-center justify-end gap-2">
                      <button onClick={() => openEditModal(user)} className="text-gray-400 hover:text-indigo-600">
                        <Edit className="w-4 h-4" />
                      </button>
                      <button onClick={() => confirmDelete(user.id)} className="text-gray-400 hover:text-red-600">
                        <Trash2 className="w-4 h-4" />
                      </button>
                    </div>
                  </td>
                </tr>
              ))}
            </tbody>
          </table>
        </div>
      </div>

      <UserModal 
        isOpen={isModalOpen}
        onClose={() => setIsModalOpen(false)}
        onSave={handleSave}
        user={editingUser}
      />

      <ConfirmationModal
        isOpen={deleteConfirmation.isOpen}
        onClose={() => setDeleteConfirmation({ ...deleteConfirmation, isOpen: false })}
        onConfirm={handleDelete}
        title="Supprimer l'utilisateur"
        message="Êtes-vous sûr de vouloir supprimer cet utilisateur ?"
      />
    </div>
  );
}
